# CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person0_nonestandar/pretrain/checkpoint-24-350/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person0_nonestandar/finetune --train_yaml ../dataset/personal_0/firsthalf/train.yaml --data_dir ../dataset/personal_0/firsthalf/ --val_yaml ../dataset/personal_0/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4

# CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person1_nonestandar/pretrain/checkpoint-24-350/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person1_nonestandar/finetune --train_yaml ../dataset/personal_1/firsthalf/train.yaml --data_dir ../dataset/personal_1/firsthalf/ --val_yaml ../dataset/personal_1/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4

# CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person2_nonestandar/pretrain/checkpoint-24-325/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person2_nonestandar/finetune --train_yaml ../dataset/personal_2/firsthalf/train.yaml --data_dir ../dataset/personal_2/firsthalf/ --val_yaml ../dataset/personal_2/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4

# CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person3_nonestandar/pretrain/checkpoint-24-350/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person3_nonestandar/finetune --train_yaml ../dataset/personal_3/firsthalf/train.yaml --data_dir ../dataset/personal_3/firsthalf/ --val_yaml ../dataset/personal_3/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4

# CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person4_nonestandar/pretrain/checkpoint-24-350/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person4_nonestandar/finetune --train_yaml ../dataset/personal_4/firsthalf/train.yaml --data_dir ../dataset/personal_4/firsthalf/ --val_yaml ../dataset/personal_4/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4

# CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person5_nonestandar/pretrain/checkpoint-24-300/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person5_nonestandar/finetune --train_yaml ../dataset/personal_5/firsthalf/train.yaml --data_dir ../dataset/personal_5/firsthalf/ --val_yaml ../dataset/personal_5/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4

CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person6_nonestandar/pretrain/checkpoint-24-300/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person6_nonestandar/finetune --train_yaml ../dataset/personal_6/firsthalf/train.yaml --data_dir ../dataset/personal_6/firsthalf/ --val_yaml ../dataset/personal_6/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4

CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person7_nonestandar/pretrain/checkpoint-24-300/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person7_nonestandar/finetune --train_yaml ../dataset/personal_7/firsthalf/train.yaml --data_dir ../dataset/personal_7/firsthalf/ --val_yaml ../dataset/personal_7/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4

CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person8_nonestandar/pretrain/checkpoint-24-325/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person8_nonestandar/finetune --train_yaml ../dataset/personal_8/firsthalf/train.yaml --data_dir ../dataset/personal_8/firsthalf/ --val_yaml ../dataset/personal_8/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4


