 CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/checkpoint-29-66420/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 16 --num_train_epochs 25 --save_steps 100 --output_dir ../models/person0_nonestandar/pretrain --train_yaml ../dataset/personal_0/train_s/train.yaml --data_dir ../dataset/personal_0/train_s/ --val_yaml ../dataset/personal_0/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4

CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/checkpoint-29-66420/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 16 --num_train_epochs 25 --save_steps 100 --output_dir ../models/person1_nonestandar/pretrain --train_yaml ../dataset/personal_1/train_s/train.yaml --data_dir ../dataset/personal_1/train_s/ --val_yaml ../dataset/personal_1/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4
 CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/checkpoint-29-66420/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 16 --num_train_epochs 25 --save_steps 100 --output_dir ../models/person2_nonestandar/pretrain --train_yaml ../dataset/personal_2/train_s/train.yaml --data_dir ../dataset/personal_2/train_s/ --val_yaml ../dataset/personal_2/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4
 CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/checkpoint-29-66420/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 16 --num_train_epochs 25 --save_steps 100 --output_dir ../models/person3_nonestandar/pretrain --train_yaml ../dataset/personal_3/train_s/train.yaml --data_dir ../dataset/personal_3/train_s/ --val_yaml ../dataset/personal_3/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4
 CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/checkpoint-29-66420/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 16 --num_train_epochs 25 --save_steps 100 --output_dir ../models/person4_nonestandar/pretrain --train_yaml ../dataset/personal_4/train_s/train.yaml --data_dir ../dataset/personal_4/train_s/ --val_yaml ../dataset/personal_4/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4
CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/checkpoint-29-66420/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 16 --num_train_epochs 25 --save_steps 100 --output_dir ../models/person5_nonestandar/pretrain --train_yaml ../dataset/personal_5/train_s/train.yaml --data_dir ../dataset/personal_5/train_s/ --val_yaml ../dataset/personal_5/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4
 CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/checkpoint-29-66420/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 16 --num_train_epochs 25 --save_steps 100 --output_dir ../models/person6_nonestandar/pretrain --train_yaml ../dataset/personal_6/train_s/train.yaml --data_dir ../dataset/personal_6/train_s/ --val_yaml ../dataset/personal_6/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4
 CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/checkpoint-29-66420/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 16 --num_train_epochs 25 --save_steps 100 --output_dir ../models/person7_nonestandar/pretrain --train_yaml ../dataset/personal_7/train_s/train.yaml --data_dir ../dataset/personal_7/train_s/ --val_yaml ../dataset/personal_7/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4
 CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/checkpoint-29-66420/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 16 --num_train_epochs 25 --save_steps 100 --output_dir ../models/person8_nonestandar/pretrain --train_yaml ../dataset/personal_8/train_s/train.yaml --data_dir ../dataset/personal_8/train_s/ --val_yaml ../dataset/personal_8/lasthalf/train.yaml --max_seq_length 90 --max_gen_length 40 --num_beams 4

