CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person0/pretrain/checkpoint-49-450/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person0/finetune --train_yaml ../dataset/personal_0/eval_0_firsthalf/train.yaml --data_dir ../dataset/personal_0/eval_0_firsthalf/ --val_yaml ../dataset/personal_0/eval_0_lasthalf/train.yaml --num_beams 4 --max_seq_length 90 --max_gen_length 40

CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person1/pretrain/checkpoint-49-500/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person1/finetune --train_yaml ../dataset/personal_1/eval_1_firsthalf/train.yaml --data_dir ../dataset/personal_1/eval_1_firsthalf/ --val_yaml ../dataset/personal_1/eval_1_lasthalf/train.yaml --num_beams 4 --max_seq_length 90 --max_gen_length 40

CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person2/pretrain/checkpoint-49-450/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person2/finetune --train_yaml ../dataset/personal_2/eval_2_firsthalf/train.yaml --data_dir ../dataset/personal_2/eval_2_firsthalf/ --val_yaml ../dataset/personal_2/eval_2_lasthalf/train.yaml --num_beams 4 --max_seq_length 90 --max_gen_length 40

CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person3/pretrain/checkpoint-49-450/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person3/finetune --train_yaml ../dataset/personal_3/eval_3_firsthalf/train.yaml --data_dir ../dataset/personal_3/eval_3_firsthalf/ --val_yaml ../dataset/personal_3/eval_3_lasthalf/train.yaml --num_beams 4 --max_seq_length 90 --max_gen_length 40

CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person4/pretrain/checkpoint-49-500/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person4/finetune --train_yaml ../dataset/personal_4/eval_4_firsthalf/train.yaml --data_dir ../dataset/personal_4/eval_4_firsthalf/ --val_yaml ../dataset/personal_4/eval_4_lasthalf/train.yaml --num_beams 4 --max_seq_length 90 --max_gen_length 40

CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person5/pretrain/checkpoint-49-400/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person5/finetune --train_yaml ../dataset/personal_5/eval_5_firsthalf/train.yaml --data_dir ../dataset/personal_5/eval_5_firsthalf/ --val_yaml ../dataset/personal_5/eval_5_lasthalf/train.yaml --num_beams 4 --max_seq_length 90 --max_gen_length 40

CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person6/pretrain/checkpoint-49-400/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person6/finetune --train_yaml ../dataset/personal_6/eval_6_firsthalf/train.yaml --data_dir ../dataset/personal_6/eval_6_firsthalf/ --val_yaml ../dataset/personal_6/eval_6_lasthalf/train.yaml --num_beams 4 --max_seq_length 90 --max_gen_length 40

CUDA_VISIBLE_DEVICES=1 python oscar/run_captioning.py --model_name_or_path ../models/person8/pretrain/checkpoint-49-450/ --do_train --do_lower_case --evaluate_during_training --add_od_labels --learning_rate 0.00005 --per_gpu_train_batch_size 1 --num_train_epochs 1 --save_steps 1 --output_dir ../models/person8/finetune --train_yaml ../dataset/personal_8/eval_8_firsthalf/train.yaml --data_dir ../dataset/personal_8/eval_8_firsthalf/ --val_yaml ../dataset/personal_8/eval_8_lasthalf/train.yaml --num_beams 4 --max_seq_length 90 --max_gen_length 40


